ALTER TABLE shops ADD COLUMN IF NOT EXISTS address_line_1 TEXT;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS address_line_2 TEXT;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS district TEXT;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS registration_number TEXT;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS tpin TEXT;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS vat_registered BOOLEAN DEFAULT FALSE;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS vat_number TEXT;
