ALTER TABLE shops ADD COLUMN IF NOT EXISTS opening_time TIME DEFAULT '08:00';
ALTER TABLE shops ADD COLUMN IF NOT EXISTS closing_time TIME DEFAULT '18:00';
ALTER TABLE shops ADD COLUMN IF NOT EXISTS is_manually_closed BOOLEAN DEFAULT FALSE;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS manually_closed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS manually_closed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL;
